# Generated by Django 4.2.17 on 2024-12-15 20:36

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TestCase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('relative_path', models.CharField(max_length=300)),
                ('create_date', models.DateTimeField(default=datetime.datetime(2024, 12, 15, 15, 36, 3, 712805))),
            ],
        ),
        migrations.CreateModel(
            name='TestRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('suite_id', models.CharField(max_length=30)),
                ('status', models.CharField(choices=[('PASS', 'Pass'), ('FAIL', 'Fail'), ('ERROR', 'Error'), ('UNKNOWN', 'Unknown'), ('XFAIL', 'Xfail'), ('XPASS', 'Xpass'), ('SKIPPED', 'Skipped'), ('INPROGRESS', 'Inprogress')], default='UNKNOWN', max_length=30)),
                ('start_time', models.DateTimeField(default=datetime.datetime(2024, 12, 15, 15, 36, 3, 713168))),
                ('end_time', models.DateTimeField(null=True)),
                ('marks', models.CharField(blank=True, max_length=30)),
                ('product_version', models.CharField(blank=True, max_length=30)),
                ('environment', models.CharField(blank=True, max_length=200)),
                ('defects', models.CharField(blank=True, max_length=100)),
                ('test_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='test_runs', to='testcases.testcase')),
            ],
        ),
    ]
